baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "TULAKEEY"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
images = ["img/wireless-backup-camera-for-trucks.jpg", "img/44.jpg"]